export const en = {
  brand: "TierYourLife",
  tagline: "Web app",
  nav: {
    signIn: "Sign in",
    signOut: "Sign out",
    account: "Your account",
    you: "You",
    yourRankings: "Your rankings",
    myLists: "My lists",
    makeList: "Make a list",
    signInFailed: "Could not sign in. Try again.",
    keepOnPhone: "Keep your lists on your phone",
    theme: "Theme",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
    settings: "Settings",
    reports: "Reports",
  },
  mod: {
    title: "Reports",
    notAvailable: "This page isn’t available.",
    listCount: { one: "{n} list", other: "{n} lists" },
    reportCount: { one: "{n} report", other: "{n} reports" },
    nothingPending: "Nothing waiting",
    blurCovers: "Blur covers",
    revealCover: "Show this cover",
    cover: "Cover",
    noCover: "No cover",
    hiddenPill: "Hidden while it waits",
    alreadyKept: "Kept once already, so reports no longer hide it",
    moreNotes: { one: "Show {n} more note", other: "Show {n} more notes" },
    today: "today",
    yesterday: "yesterday",
    daysAgo: { one: "{n} day ago", other: "{n} days ago" },
    consequence: "Taking it down leaves the author’s own copy untouched.",
    leaveUp: "Leave it up",
    takeDown: "Take it down",
    acting: "Saving…",
    openList: "Open list",
    banQuestion: "Take it down. Ban the author?",
    banNone: "No ban",
    banWeek: "A week",
    banMonth: "A month",
    banThreeMonths: "Three months",
    banSixMonths: "Six months",
    banForever: "Forever",
    cancel: "Cancel",
    foreverTitle: "Ban {name} forever?",
    foreverBody: "They will never publish again.",
    banForeverAction: "Ban forever",
    takenDown: "Taken down.",
    takenDownBanned: "Taken down. {name} banned {length}.",
    bannedWeek: "for a week",
    bannedMonth: "for a month",
    bannedThreeMonths: "for three months",
    bannedSixMonths: "for six months",
    bannedForever: "forever",
    leftUp: "Left up. Reports no longer hide it.",
    failedDecision: "Couldn’t save the decision — nothing changed.",
    tryAgain: "Try again",
    failed: "Could not load the reports.",
    emptyTitle: "Nothing to review",
    emptyBody: "Complaints about community lists arrive here.",
  },
  settings: {
    title: "Settings",
    guestTitle: "Sign in to change your settings.",
    guestBody:
      "Your name, your picture and the theme belong to an account. Ranking a list doesn’t need one.",
    themeGuestNote: "Saved on this device while you’re signed out.",
    nameTitle: "Your name",
    nameBody: "The name shown as the author on every list you publish. Your email is never shown.",
    nameField: "Name",
    nameCounter: "{n} / {max}",
    nameNeeded: "A name is needed — it’s what people see.",
    nameNote:
      "Lists you already published keep the old name until we update them — that happens right after you save.",
    save: "Save",
    cancel: "Cancel",
    saving: "Saving…",
    savedPublishing: "Saved. Updating your published lists…",
    saved: "Saved.",
    nameFailed: "Couldn’t save — the server didn’t answer. Your name is unchanged.",
    tryAgain: "Try again",
    faceTitle: "Your face",
    faceBody: "Pick a picture from a list you published. Nothing is uploaded.",
    faceNone: "Publish a list and its pictures show up here.",
    faceChoices: "Your face",
    faceChoice: "Card from {list}",
    faceLetter: "Just the letter",
    faceLetterCaption: "Letter",
    faceFailed: "Couldn’t save — the server didn’t answer.",
    privacyTitle: "Privacy",
    signOutNote:
      "Your lists and rankings stay — sign in with the same Google account to get them back.",
    deleteAction: "Delete account",
    deleteHelper:
      "Everything goes: your lists, your name and the pictures behind them. Rankings keep their links, without your name.",
    deleteTitle: "Delete this account?",
    deleteBody:
      "The account goes, and with it the copy of your boards, everything you published and the pictures behind it. This cannot be undone.",
    deleteConfirm: "Delete for good",
    deleting: "Deleting…",
    deleteFailed: "Couldn’t delete the account — nothing was changed. Try again in a minute.",
    deleted: "Your account was deleted.",
    languageTitle: "Language",
    hiddenTitle: "Hidden",
    hiddenBody: "Lists and authors you hid on this device. Nobody else is told.",
    hiddenAuthor: "Everything from {name}",
    showAgain: "Show again",
  },
  footer: {
    privacy: "Privacy policy",
    about: "About",
  },
  about: {
    title: "About",
    what: "Rank anything into tiers, or take someone else's list and rank it your way. Ranking a list needs no account.",
    creditsTitle: "Credits",
    catalogue: "The details and pictures of films, series and people come from TMDB.",
    tmdbLogo: "TMDB",
    // TMDB's terms give this sentence word for word.
    tmdb: "This product uses the TMDB API but is not endorsed or certified by TMDB.",
    dataTitle: "Your data",
    deleteAccount: "Delete your account",
  },
  home: {
    hero: "Rank anything, or take someone else's list and rank it your way.",
    searchPlaceholder: "Search lists — anime, games, films…",
    categories: "Categories",
    popular: "Popular",
    popularNote: "Open one and start dragging. No account needed.",
    source: "Whose lists to show",
    // "All" is the phone app's word for the same switch.
    everyone: "All",
    following: "Following",
    followingHeading: "New from people you follow",
    newestFirst: "Newest first.",
    followingNobody: "You aren’t following anyone",
    followingNobodyBody: "Follow someone and their new lists arrive here first.",
    worthFollowing: "People worth following",
    followingNothing: "Nobody you follow has published anything yet.",
    seeEveryone: "See all lists",
    followingFailed: "Couldn’t load your feed.",
  },
  profile: {
    someone: "Someone",
    followers: { one: "{n} follower", other: "{n} followers" },
    publicLists: { one: "{n} public list", other: "{n} public lists" },
    publicListsMore: { one: "{n}+ public list", other: "{n}+ public lists" },
    editInSettings: "Edit in Settings",
    lists: "Lists",
    newestFirst: "newest first",
    noLists: "No public lists yet.",
    hiddenAuthor: "You hid everything from this person.",
  },
  follow: {
    follow: "Follow",
    following: "Following",
    unfollow: "Unfollow",
    unfollowed: "Unfollowed {name}",
    undo: "Undo",
    failed: "Couldn’t follow — try again.",
    cancel: "Cancel",
    signInTitle: "Sign in to follow",
    signInBody: "Following keeps new lists from people you like at the top of your feed.",
  },
  search: {
    title: "“{q}”",
    browse: "Browse lists",
    results: "Search results",
    count: { one: "{n} list", other: "{n} lists" },
    countMore: { one: "{n} list, and more", other: "{n} lists, and more" },
    sortBy: "Order",
    mostRanked: "Most ranked",
    newest: "Newest",
    categories: "Category",
    all: "All",
    nothing: "Nothing with that name yet.",
    browseHint: "Try fewer words, or browse {where}.",
    browseHome: "the front page",
    popularIn: "Popular in {category}",
    makeThis: "Make this list",
  },
  new: {
    title: "Make a list",
    guestNote: "Sign in when you publish. Until then the draft stays on this device.",
    preview: "Preview",
    back: "Back to editing",
    publish: "Publish",
    publishing: "Publishing…",
    about: "About the list",
    nameLabel: "Title",
    namePlaceholder: "Every A24 film, ranked",
    categoryLabel: "Category",
    cards: "Cards",
    cardsAdded: { one: "{n} added", other: "{n} added" },
    upload: "Upload images",
    uploading: { one: "Uploading {n}…", other: "Uploading {n}…" },
    pictureSignIn: "Sign in to add your own pictures; they live in your account.",
    pictureNotImage: "{name} is not a picture.",
    pictureTooBig: "{name} is too big even after shrinking.",
    pictureFailed: "{name} could not be uploaded. Try again.",
    addLabel: "Add a card",
    addPlaceholder: "Search the catalogue, or type a name",
    searchFilms: "Search films and series to add, or type a name",
    searchAnime: "Search anime to add, or type a name",
    searchPeople: "Search people to add, or type a name",
    suggestions: "Suggestions",
    fromTmdb: "From TMDB",
    searching: "Looking in the catalogue…",
    nothingFound: "Nothing in the catalogue by that name. Add it as a card anyway.",
    catalogueDown: "The catalogue is not answering. Cards by name still work.",
    addAsName: "Add “{name}” as a card",
    add: "Add",
    added: "Added",
    unnamed: "Untitled card",
    remove: "Remove {name}",
    noCardsYet: "No cards yet. Search the catalogue or type a name and press Enter.",
    tiers: "Tiers",
    // The phone app's names for the five tiers a new list starts with.
    tierBest: "Best",
    tierGreat: "Great",
    tierGood: "Good",
    tierOkay: "Okay",
    tierWorst: "Worst",
    addTier: "Add tier",
    tierUnnamed: "this tier",
    colourOf: "Colour of {name}",
    labelOf: "Label of tier {n}",
    captionOf: "Caption of {name}",
    captionPlaceholder: "Caption, optional",
    dragTier: "Drag {name} to reorder",
    moveUp: "Move {name} up",
    moveDown: "Move {name} down",
    removeTier: "Remove {name}",
    palette: "Colours",
    tiersHint:
      "Tiers start at S–D. Rename, recolour and reorder them here; the people who rank your list get them empty.",
    previewNote: "This is how the list opens for people who rank it: every card unranked.",
    untitled: "Untitled list",
    needTitle: "Give the list a title.",
    needCategory: "Pick a category.",
    needCards: "Add at least one card.",
    needTier: "Keep at least one tier.",
    needTierLabel: "Every tier needs a label.",
    tooManyTiers: "At most 20 tiers.",
    tooManyCards: "At most 2000 cards.",
    ready: "Ready to publish.",
    startOver: "Start over",
    more: "More",
    failedOffline:
      "No connection. Your draft is safe on this device; try again once you are back online.",
    failedBanned: "You cannot publish at the moment.",
    failedTooMany:
      "This account has published as many lists as it can. Unpublish one in the app first.",
    failedSignedOut: "Publishing needs an account. Sign in and try again.",
    failedTooLarge: "The list is too big to publish. {detail}",
    failedInvalid: "The list was refused. {detail}",
    failedOther: "Could not publish. Nothing was lost. Try again.",
    editTitle: "Edit list",
    editSignIn: "Sign in to edit the lists you published.",
    openingList: "Opening the list…",
    listGone: "This list isn’t published anymore.",
    listFailed: "Could not open the list. Try again.",
    tryAgain: "Try again",
    notYours: "This list was published by someone else.",
    openList: "Open the list",
    publishChanges: "Publish changes",
    discardChanges: "Discard changes",
    failedGone:
      "This list isn’t published anymore, so there is nothing to change. Make it again from Make a list.",
  },
  category: {
    anime: "Anime",
    film_tv: "Film & TV",
    games: "Games",
    music: "Music",
    books: "Books",
    food: "Food",
    sport: "Sport",
    people: "People",
    other: "Other",
  },
  feed: {
    empty: "No lists here yet.",
    allHidden: "Everything here is hidden for you. Settings has the list.",
    hiddenTile: "Hidden for you",
    undo: "Undo",
    omitted: { one: "{n} hidden list isn’t shown.", other: "{n} hidden lists aren’t shown." },
    failed: "Could not load the lists.",
    offline: "No connection. Try again once you are back online.",
    tryAgain: "Try again",
    more: "Show more",
    loadingMore: "Loading…",
    moreFailed: "Could not load more.",
  },
  list: {
    opening: "Opening the list…",
    by: "by {name}",
    home: "Go to the front page",
    tryAgain: "Try again",
    unavailableTitle: "This list isn’t available",
    unavailableBody:
      "It was taken down or is waiting for someone to look at it. Whoever sent you the link did nothing wrong.",
    unverifiedTitle: "This copy of the site could not be verified",
    unverifiedBody: "The list is still there. Try opening it in a regular browser window.",
    offlineTitle: "No connection",
    offlineBody: "Nothing was lost. Try again once you are back online.",
    failedTitle: "Could not open this list",
    failedBody: "Something went wrong on the way. Try again.",
    views: "Whose arrangement to show",
    // The phone app's words for the same switch.
    viewMine: "Mine",
    viewTheirs: "Their ranking",
    yourList: "your list",
    yourArrangement: "Your arrangement",
    more: "More about this list",
    report: "Report this list",
    hide: "Hide this list",
    hideAuthorNow: "Hide everything from {name}",
    hiddenAuthorNotice: "Everything from {name} is hidden for you",
    edit: "Edit",
    delete: "Delete",
    deleteTitle: "Delete this list?",
    deleteBody:
      "“{title}” leaves the feed and its link stops working. Rankings people already made from it stay. A board on your phone stays on your phone.",
    keepIt: "Keep it",
    deleting: "Deleting…",
    deleteFailed: "Could not delete it. Try again in a minute.",
    deleteOffline: "No connection. Try again once you are back online.",
    copyLink: "Copy link",
    share: "Share",
    linkCopied: "Link copied",
    hiddenNotice: "Hidden for you",
    undo: "Undo",
    hiddenTitle: "You hid this list",
    hiddenAuthorTitle: "You hid everything from {name}",
    hiddenBody: "It won’t show up in your feed. You can undo that here.",
    unhide: "Unhide",
    goHome: "Go to home",
  },
  report: {
    title: "Report this list",
    body: "Tell us what’s wrong with it. You can add a note.",
    why: "What is wrong with it?",
    reasonSexual: "Sexual content",
    reasonHate: "Hate or harassment",
    reasonViolence: "Violence or shocking content",
    reasonSpam: "Spam or advertising",
    reasonOther: "Something else",
    noteLabel: "Note (optional)",
    notePlaceholder: "What should the reviewer look at?",
    noteCounter: "{n} / {max}",
    hideAuthor: "Also hide everything from {name}",
    byHand: "A person reads every report. Enough of them hide a list until they do.",
    send: "Report",
    sending: "Sending…",
    cancel: "Cancel",
    failed: "Couldn’t send the report — nothing was sent. Try again in a minute.",
    sentTitle: "Reported, and hidden for you",
    sentBody: "A person reviews reports by hand. Until then it may stay up for other people.",
    done: "Done",
    signInTitle: "Sign in to report",
    signInBody:
      "Reports go to a person, so they need an account. Hiding a list doesn’t — that stays on this device.",
    hideInstead: "Hide instead",
  },
  board: {
    authorsVersion: "Author's version",
    unranked: { one: "{n} unranked", other: "{n} unranked" },
  },
  rank: {
    yours: "Your ranking",
    ownCopy: "you are ranking your own copy",
    placed: "{n} of {total} placed",
    left: { one: "{n} card left", other: "{n} cards left" },
    hintPick: "Pick a card, then tap a tier or press {keys}",
    hintPlace: "Tap a tier to place {name}, or press its number",
    hintPickTouch: "Tap a card, then a tier",
    hintPlaceTouch: "Tap a tier to place it",
    search: "Find a card",
    searchNone: "No card by that name.",
    allPlaced: { one: "The card is placed", other: "All {n} placed" },
    allPlacedNote: "Change your mind by dragging a card, or finish and get your link.",
    allPlacedNoteEdit: "Change your mind by dragging a card, or save what you have.",
    placeIn: "Place {name} in {tier}",
    undo: "Undo",
    finish: "Finish",
    cancel: "Cancel",
    saveChanges: "Save",
    savingShort: "Saving…",
    saving: "Saving your ranking…",
    live: "Your ranking is live at",
    liveNote:
      "Anyone with that link sees your version next to the author’s. It stays without an account.",
    liveNoteKept:
      "Anyone with that link sees your version next to the author’s. It’s kept in your rankings.",
    copy: "Copy link",
    copied: "Copied",
    download: "Download image",
    downloading: "Making the image…",
    downloadFailed: "Could not make the image. Try again.",
    save: "Save to my account",
    invite: "Keep your lists on your phone",
    inviteNote: "Offline, with a ranking history, AI card images and the Flip cover.",
    open: "Open",
    change: "Change ranking",
    tryAgain: "Try again",
    failedOffline:
      "No connection. Nothing was lost: your placements are safe on this device. Try again once you are back online.",
    failedGone: "This list isn’t available anymore, so the ranking cannot be kept.",
    failedOther: "Could not save the ranking. Nothing was lost. Try again.",
  },
  keep: {
    title: "Keep this ranking",
    body: "The link works either way. An account puts it in one place, lets you edit it later, and unlocks making your own lists.",
    google: "Continue with Google",
    busy: "Signing in…",
    linkOnly: "Keep the link only",
    failed: "Could not sign in. Try again, or keep the link.",
    inApp:
      "Google will not sign you in inside another app's browser. Open this page in Chrome or Safari: the menu in the corner has “Open in browser”.",
  },
  ranking: {
    opening: "Opening the ranking…",
    visitors: "Visitor's ranking",
    byVisitor: "ranked by a visitor",
    byYou: "ranked by you",
    edit: "Edit",
    editNote: "the link stays the same when you edit",
    saved: "Saved. Same link, new arrangement.",
    noAuthorVersion: "{name} hasn’t arranged this list.",
    rankYourself: "Disagree? Rank it yourself.",
    rankThis: "Rank this list",
    listGone: "The list this ranking was made from isn’t available anymore.",
    unavailableTitle: "This ranking isn’t available",
    unavailableBody: "There is nothing at this address. The link may have been copied wrong.",
    failedTitle: "Could not open this ranking",
  },
  me: {
    title: "Your rankings",
    empty: "Rankings you keep will show up here.",
    signInFirst:
      "Sign in to see the rankings you keep. Whatever you finished on this device comes along.",
    placedOf: "{placed} of {total} placed",
    failed: "Could not load your rankings.",
    tryAgain: "Try again",
    more: { one: "Only the newest {n} is shown.", other: "Only the newest {n} are shown." },
    edit: "Edit",
    fromPhone: "Lists you published from the app live in My lists.",
    browse: "Browse lists",
    tabs: "Your account",
    kept: { one: "{n} kept on this account", other: "{n} kept on this account" },
    lists: "My lists",
    signInForLists: "Sign in to see the lists you published from the app.",
    published: { one: "{n} published from the app", other: "{n} published from the app" },
    listsEmpty: "Nothing published yet.",
    listsHow:
      "In the app, open a list, add cards, set the tiers and tap Publish. It shows up here under the same Google account.",
    listsFailed: "Could not load your lists.",
    // A list made on the site has no other copy: taking it down deletes it, and the word says so.
    remove: "Delete",
    removeAsk:
      "Delete “{title}”? It leaves the feed and its link stops working. Rankings people already made from it stay. A board on your phone stays on your phone.",
    keepIt: "Keep it",
    removing: "Deleting…",
    removeFailed: "Could not delete it. Try again.",
    removeOffline: "No connection. Try again once you are back online.",
  },
  // Shown by plain DOM when the site itself could not load; see src/boot.ts.
  boot: {
    title: "The site could not start",
    body: "Part of it did not arrive: the connection dropped, or the site was updated this very minute. Reloading usually does it.",
    reload: "Reload",
  },
  notFound: {
    title: "There is nothing at this address.",
    home: "Go to the front page",
  },
  card: {
    by: "by {name}",
    items: { one: "{n} card", other: "{n} cards" },
    rankings: { one: "{n} ranking", other: "{n} rankings" },
    noArt: "No picture",
  },
} as const;
