export const en = {
  brand: "TierYourLife",
  tagline: "Web app",
  nav: {
    signIn: "Sign in",
    more: "More",
    keepOnPhone: "Keep your lists on your phone",
  },
  footer: {
    privacy: "Privacy policy",
    tmdb: "This product uses the TMDB API but is not endorsed or certified by TMDB.",
  },
  home: {
    hero: "Rank anything, or take someone else's list and rank it your way.",
    searchPlaceholder: "Search lists — anime, games, films…",
    searchSoon: "Search is on its way.",
  },
  list: {
    opening: "Opening the list…",
    by: "by {name}",
    home: "Go to the front page",
    tryAgain: "Try again",
    unavailableTitle: "This list isn’t available",
    unavailableBody:
      "It was taken down or is waiting for someone to look at it. Whoever sent you the link did nothing wrong.",
    unverifiedTitle: "This copy of the site could not be verified",
    unverifiedBody: "The list is still there. Try opening it in a regular browser window.",
    offlineTitle: "No connection",
    offlineBody: "Nothing was lost. Try again once you are back online.",
    failedTitle: "Could not open this list",
    failedBody: "Something went wrong on the way. Try again.",
    views: "Whose arrangement to show",
  },
  board: {
    authorsVersion: "Author's version",
    unranked: { one: "{n} unranked", other: "{n} unranked" },
  },
  rank: {
    yours: "Your ranking",
    ownCopy: "you are ranking your own copy",
    placed: "{n} of {total} placed",
    left: { one: "{n} item left", other: "{n} items left" },
    hintPick: "Pick a card, then tap a tier or press {keys}",
    hintPlace: "Tap a tier to place {name}, or press its number",
    placeIn: "Place {name} in {tier}",
    undo: "Undo",
    finish: "Finish",
    saving: "Saving your ranking…",
    live: "Your ranking is live at",
    liveNote:
      "Anyone with that link sees your version next to the author’s. It stays without an account.",
    copy: "Copy link",
    copied: "Copied",
    download: "Download image",
    downloading: "Making the image…",
    downloadFailed: "Could not make the image. Try again.",
    open: "Open",
    change: "Change ranking",
    tryAgain: "Try again",
    failedOffline:
      "No connection. Nothing was lost: your placements are safe on this device. Try again once you are back online.",
    failedGone: "This list isn’t available anymore, so the ranking cannot be kept.",
    failedOther: "Could not save the ranking. Nothing was lost. Try again.",
  },
  ranking: {
    opening: "Opening the ranking…",
    visitors: "Visitor's ranking",
    byVisitor: "ranked by a visitor",
    byYou: "ranked by you",
    noAuthorVersion: "{name} hasn’t arranged this list.",
    rankYourself: "Disagree? Rank it yourself.",
    listGone: "The list this ranking was made from isn’t available anymore.",
    unavailableTitle: "This ranking isn’t available",
    unavailableBody: "There is nothing at this address. The link may have been copied wrong.",
    failedTitle: "Could not open this ranking",
  },
  me: {
    title: "Your rankings",
    empty: "Rankings you keep will show up here.",
  },
  notFound: {
    title: "There is nothing at this address.",
    home: "Go to the front page",
  },
  card: {
    by: "by {name}",
    items: { one: "{n} item", other: "{n} items" },
    rankings: { one: "{n} ranking", other: "{n} rankings" },
    noArt: "No picture",
  },
} as const;
